// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Approve: typeof import('./src/views/Approve.vue')['default']
    BButton: typeof import('bootstrap-vue')['BButton']
    BCard: typeof import('bootstrap-vue')['BCard']
    BCo: typeof import('bootstrap-vue')['BCo']
    BCol: typeof import('bootstrap-vue')['BCol']
    BCollapse: typeof import('bootstrap-vue')['BCollapse']
    BCon: typeof import('bootstrap-vue')['BCon']
    BContaienr: typeof import('bootstrap-vue')['BContaienr']
    BContainer: typeof import('bootstrap-vue')['BContainer']
    BIconCircleFill: typeof import('bootstrap-vue')['BIconCircleFill']
    BLink: typeof import('bootstrap-vue')['BLink']
    BListGroup: typeof import('bootstrap-vue')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue')['BListGroupItem']
    BNavbar: typeof import('bootstrap-vue')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue')['BNavItem']
    BOverlay: typeof import('bootstrap-vue')['BOverlay']
    BRo: typeof import('bootstrap-vue')['BRo']
    BRow: typeof import('bootstrap-vue')['BRow']
    History: typeof import('./src/views/History.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Overview: typeof import('./src/views/Overview.vue')['default']
    Propose: typeof import('./src/views/Propose.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
