// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    BButton: typeof import('bootstrap-vue')['BButton']
    BCard: typeof import('bootstrap-vue')['BCard']
    BCardBody: typeof import('bootstrap-vue')['BCardBody']
    BCol: typeof import('bootstrap-vue')['BCol']
    BCollapse: typeof import('bootstrap-vue')['BCollapse']
    BContainer: typeof import('bootstrap-vue')['BContainer']
    BForm: typeof import('bootstrap-vue')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue')['BFormInput']
    BIconArrowClockwise: typeof import('bootstrap-vue')['BIconArrowClockwise']
    BIconCheckCircle: typeof import('bootstrap-vue')['BIconCheckCircle']
    BIconCircleFill: typeof import('bootstrap-vue')['BIconCircleFill']
    BIconHourglassSplit: typeof import('bootstrap-vue')['BIconHourglassSplit']
    BIconXCircle: typeof import('bootstrap-vue')['BIconXCircle']
    BLink: typeof import('bootstrap-vue')['BLink']
    BListGroup: typeof import('bootstrap-vue')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue')['BListGroupItem']
    BModal: typeof import('bootstrap-vue')['BModal']
    BNavbar: typeof import('bootstrap-vue')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue')['BNavItem']
    BOverlay: typeof import('bootstrap-vue')['BOverlay']
    BRow: typeof import('bootstrap-vue')['BRow']
    BSpinner: typeof import('bootstrap-vue')['BSpinner']
    BTable: typeof import('bootstrap-vue')['BTable']
    History: typeof import('./src/views/History.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Operations: typeof import('./src/views/Operations.vue')['default']
    Overview: typeof import('./src/views/Overview.vue')['default']
    Proposal: typeof import('./src/views/Proposal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TxModal: typeof import('./src/components/TxModal.vue')['default']
  }
}
